# Generated by Django 2.1.7 on 2019-03-07 03:13

from django.db import migrations, models
import django.db.models.deletion
import retriever.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EastonBjjClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attire', models.CharField(choices=[(retriever.models.EastonBjjAttire('Gi'), 'Gi'), (retriever.models.EastonBjjAttire('No-gi'), 'No-gi')], max_length=2)),
                ('category', models.CharField(choices=[(retriever.models.EastonBjjCat('Drilling/Training'), 'Drilling/Training'), (retriever.models.EastonBjjCat('Randori'), 'Randori')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EastonClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym', models.CharField(choices=[(retriever.models.EastonGym('Arvada'), 'Arvada'), (retriever.models.EastonGym('Aurora'), 'Aurora'), (retriever.models.EastonGym('Boulder'), 'Boulder'), (retriever.models.EastonGym('Castle Rock'), 'Castle Rock'), (retriever.models.EastonGym('Centennial'), 'Centennial'), (retriever.models.EastonGym('Denver'), 'Denver'), (retriever.models.EastonGym('Littleton'), 'Littleton'), (retriever.models.EastonGym('Thornton'), 'Thornton')], max_length=2)),
                ('category', models.CharField(choices=[(retriever.models.EastonClassCategory('MMA'), 'MMA'), (retriever.models.EastonClassCategory('BJJ'), 'BJJ'), (retriever.models.EastonClassCategory('Striking'), 'Striking'), (retriever.models.EastonClassCategory('Wrestling'), 'Wrestling'), (retriever.models.EastonClassCategory('Conditioning'), 'Conditioning'), (retriever.models.EastonClassCategory('Yoga'), 'Yoga'), (retriever.models.EastonClassCategory('Open Gym'), 'Open Gym'), (retriever.models.EastonClassCategory('Private Lesson'), 'Private Lesson'), (retriever.models.EastonClassCategory('Little Tigers'), 'Little Tigers'), (retriever.models.EastonClassCategory('Kids BJJ'), 'Kids BJJ'), (retriever.models.EastonClassCategory('Kids Striking'), 'Kids Striking'), (retriever.models.EastonClassCategory('Kids Wrestling'), 'Kids Wrestling'), (retriever.models.EastonClassCategory('Not Set'), 'Not Set')], default=retriever.models.EastonClassCategory('Not Set'), max_length=3)),
                ('class_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('requirements', models.CharField(choices=[(retriever.models.EastonRequirements('Invitation'), 'Invitation'), (retriever.models.EastonRequirements('Green shirt, four stripe white belt'), 'Green shirt, four stripe white belt'), (retriever.models.EastonRequirements('Two stripes or wrestling experience'), 'Two stripes or wrestling experience'), (retriever.models.EastonRequirements('Over 40 years old'), 'Over 40 years old'), (retriever.models.EastonRequirements('Female'), 'Female'), (retriever.models.EastonRequirements('Over 200 pounds'), 'Over 200 pounds'), (retriever.models.EastonRequirements('Two stripes, under 160 pounds'), 'Two stripes, under 160 pounds'), (retriever.models.EastonRequirements('Blue shirt'), 'Blue shirt'), (retriever.models.EastonRequirements('Green shirt'), 'Green shirt'), (retriever.models.EastonRequirements('Orange shirt'), 'Orange shirt'), (retriever.models.EastonRequirements('Yellow shirt'), 'Yellow shirt'), (retriever.models.EastonRequirements('Purple belt'), 'Purple belt'), (retriever.models.EastonRequirements('Blue belt'), 'Blue belt'), (retriever.models.EastonRequirements('White belt two stripes'), 'White belt two stripes'), (retriever.models.EastonRequirements('Yellow belt'), 'Yellow belt'), (retriever.models.EastonRequirements('Solid grey belt'), 'Solid grey belt'), (retriever.models.EastonRequirements('Grey/white belt'), 'Grey/white belt'), (retriever.models.EastonRequirements('None'), 'None'), (retriever.models.EastonRequirements('Not set'), 'Not set')], default=retriever.models.EastonClassCategory('Not Set'), max_length=3)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('canceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EastonStrClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(retriever.models.EastonStrCat('Kickboxing'), 'Kickboxing'), (retriever.models.EastonStrCat('Muay thai'), 'Muay thai'), (retriever.models.EastonStrCat('Sparring'), 'Sparring')], max_length=2)),
                ('easton_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retriever.EastonClass')),
            ],
        ),
        migrations.AddField(
            model_name='eastonbjjclass',
            name='easton_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retriever.EastonClass'),
        ),
    ]
